import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Flag from './Flag'
import TeamLogo from './TeamLogo'
import { RailCard } from './MatchRail'
import { TIER_STYLES, ratingTierIndex } from './PerformanceStrip'
import { rating as fmtRating, num, dateRangeLabel } from '../lib/format'

// Domain the mini bars scale against -- same [0.4, 1.8] PerformanceStrip's
// own Rating 2.0 stat uses, so a bar drawn here reads the same height it
// would in the full strip rather than inventing its own scale.
const MINI_DOMAIN = [0.4, 1.8]
// Taller now that the card no longer spends height on the ACS/K-D/ADR/KAST/
// HS%/Maps stat grid below the identity row (removed per direct request,
// leaving Rating -- already shown big next to the photo -- as the card's
// only headline number) -- that freed space went straight into these bars
// rather than just shrinking the card.
const MINI_BAR_MAX_PX = 64
const MINI_BAR_MIN_PX = 6
// Most recent on the right, oldest on the left -- newest maps at the same
// visual "reading end" as the full PerformanceStrip's own RTL-scrolled view.
const MINI_MAP_COUNT = 6

/**
 * rft.gg's "PLAYER OF THE MONTH" panel, adapted to a rolling 7-day window
 * instead -- "Player of the Week", per direct request (a calendar month is
 * long relative to how often this should actually change against a season
 * with weekly brackets).
 *
 * Shows the player's real photo, same manifest/fallback treatment as
 * PlayerProfile's own header (`player_photos` scraper manifest, silhouette
 * placeholder + accent halo when there's no real photo on file or it fails
 * to load).
 *
 * Narrow rail layout only -- this used to also render as a full-width
 * horizontal banner (a `wide` prop) for Tournaments.jsx's centre column, but
 * that placement moved back into the left rail (280px, widened from its
 * original 220px specifically to give the mini strip below more room), so
 * `wide` had no remaining caller and was removed rather than kept as dead
 * code. Recoverable from git history if a wide placement is wanted again.
 *
 * The sample size (maps/rounds) is still stated outright. The week is often
 * only partly played through, and a 1.45 rating off 4 maps means something
 * different from a 1.45 off 30 -- see build_player_week.py for how the
 * WINNER is chosen (a Wilson-lower-bound confidence score, the same
 * technique aggregateKdByCountry uses in playerDuels.js, so a one-map hot
 * streak can't outrank a whole week of consistent play); the `rating`
 * shown here is still the player's real, unshrunk average either way.
 *
 * Renders nothing when player_week.json is absent (it's generated by
 * data_prep/build_player_week.py and may legitimately not exist yet).
 *
 * `mapRows` (optional, PlayerProfile-shaped rows from
 * playerMapPerformance.js's buildPlayerMapPerformance -- one entry per map
 * this player played, oldest first) adds a compact recent-form strip under
 * the identity row: a handful of small Rating 2.0 badges over short bars,
 * coloured by the same tier scale PerformanceStrip.jsx uses for its own
 * full-size version, per direct request modelled on rft.gg's own "Player of
 * the Month" widget (which embeds a mini version of its performance chart
 * directly in the card rather than linking out to a separate one). Omitted
 * entirely -- not just empty -- when there's nothing to show yet, same as
 * every other data-optional piece of this card.
 */
export default function PlayerOfWeekCard({ data, photosData, mapRows }) {
  const photoPath = data?.player ? photosData?.[data.player.toLowerCase()] : null
  const [photoLoadFailed, setPhotoLoadFailed] = useState(false)
  useEffect(() => {
    setPhotoLoadFailed(false)
  }, [data?.player])

  if (!data?.player) return null

  const hasPhoto = photoPath && !photoLoadFailed

  return (
    <RailCard title={`Player of the week · ${dateRangeLabel(data.weekStart, data.weekEnd)}`}>
      <div className="p-4 flex flex-col gap-4">
        <div className="flex items-center gap-4 shrink-0">
          {/* Photo/text sizes bumped up from this card's original rail
              sizing (w-16 photo, text-[15px] name, text-xl rating) -- the
              same numbers this card's own former `wide` variant used, now
              applied unconditionally since the rail itself widened to 280px
              (from 220px) and the old sizing left visible dead space beside
              short text like a name/team tag, per direct request to make
              this identity row actually use the extra width rather than
              just leaving it blank down the right side.

              Same photo-frame treatment as PlayerProfile's header: a
              blurred accent halo behind the EMPTY placeholder only (a real
              photo has its own colors/edges the halo just fights with). */}
          <div className="relative w-20 h-20 shrink-0">
            {!hasPhoto && (
              <div className="absolute inset-0 rounded-xl bg-accent/25 blur-2xl" aria-hidden="true" />
            )}
            <div className="relative w-full h-full rounded-xl bg-surface2 border border-hairline flex items-center justify-center overflow-hidden">
              {hasPhoto ? (
                <img
                  src={`${import.meta.env.BASE_URL}${photoPath}`}
                  alt={data.player}
                  className="w-full h-full object-cover"
                  onError={() => setPhotoLoadFailed(true)}
                />
              ) : (
                <svg viewBox="0 0 24 24" fill="none" className="w-10 h-10 text-muted/40" aria-hidden="true">
                  <circle cx="12" cy="8" r="4" stroke="currentColor" strokeWidth="1.5" />
                  <path d="M4 20.5c0-4.42 3.58-7.5 8-7.5s8 3.08 8 7.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
                </svg>
              )}
            </div>
          </div>

          <div className="min-w-0 flex-1">
            <Link
              to={`/players/${encodeURIComponent(data.player)}`}
              className="flex items-center gap-1.5 font-semibold text-ink transition-colors hover:text-accent-bright text-lg"
            >
              {data.countryCode && (
                <Flag countryCode={data.countryCode} countryName={data.countryName} size={14} />
              )}
              <span className="truncate">{data.player}</span>
            </Link>
            {data.team && (
              <Link
                to={`/teams/${encodeURIComponent(data.team)}`}
                className="mt-1 flex min-w-0 items-center text-[11px] text-muted transition-colors hover:text-ink"
              >
                <TeamLogo team={data.team} size={14} />
              </Link>
            )}
            <div className="mt-1.5 flex items-baseline gap-1">
              <span className="font-display font-bold leading-none text-accent-bright text-2xl">
                {fmtRating(data.rating)}
              </span>
              <span className="text-[9px] uppercase tracking-wide text-muted/70">Rating</span>
            </div>
            {/* Moved off its own centered full-width line and into this
                column instead, right under the number it's qualifying --
                per direct request, now that the identity row has the width
                to hold it without crowding the name/team lines above. */}
            <p className="mt-0.5 text-[10px] text-muted/60">
              {num(data.rounds)} rounds this week
            </p>
          </div>
        </div>

        {mapRows?.length > 0 && (
          <div className="flex items-end justify-center gap-1.5 pt-1 border-t border-hairline">
            {mapRows.slice(-MINI_MAP_COUNT).map((r) => {
              const style = r.rating != null ? TIER_STYLES[ratingTierIndex(r.rating)] : null
              const [min, max] = MINI_DOMAIN
              const clamped = r.rating != null ? Math.min(max, Math.max(min, r.rating)) : min
              const heightPx = r.rating != null
                ? MINI_BAR_MIN_PX + ((clamped - min) / (max - min)) * (MINI_BAR_MAX_PX - MINI_BAR_MIN_PX)
                : MINI_BAR_MIN_PX
              return (
                <div key={r.id} className="flex flex-1 flex-col items-center gap-1 pt-3.5">
                  {r.rating != null && (
                    <span
                      className={`text-[9px] font-bold leading-none rounded px-1 py-0.5 ${style.bg} ${style.text}`}
                    >
                      {r.rating.toFixed(2)}
                    </span>
                  )}
                  <div
                    className={`w-full max-w-[18px] rounded-t ${style ? '' : 'bg-surface2'}`}
                    style={{
                      height: `${heightPx}px`,
                      background: style
                        ? `linear-gradient(rgba(${style.hex}, 0.4), rgba(${style.hex}, 0.05))`
                        : undefined,
                    }}
                  />
                </div>
              )
            })}
          </div>
        )}
      </div>
    </RailCard>
  )
}
