import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import Flag from './Flag'
import TeamLogo from './TeamLogo'
import { RailCard } from './MatchRail'
import { rating as fmtRating, pct, num, dateRangeLabel } from '../lib/format'

/**
 * rft.gg's "PLAYER OF THE MONTH" panel, adapted to a rolling 7-day window
 * instead -- "Player of the Week", per direct request (a calendar month is
 * long relative to how often this should actually change against a season
 * with weekly brackets).
 *
 * Shows the player's real photo, same manifest/fallback treatment as
 * PlayerProfile's own header (`player_photos` scraper manifest, silhouette
 * placeholder + accent halo when there's no real photo on file or it fails
 * to load).
 *
 * `wide`: renders as a full-width horizontal banner (photo | identity |
 * divider | stat row) instead of the narrow rail's stacked layout -- used
 * on Tournaments.jsx under the Events list rather than in the 220px left
 * rail, per direct request: a photo big enough to read plus a 3-column stat
 * grid read as cramped at rail width, and there was no rail-width
 * constraint forcing it to stay there.
 *
 * The sample size (maps/rounds) is still stated outright. The week is often
 * only partly played through, and a 1.45 rating off 4 maps means something
 * different from a 1.45 off 30 -- see build_player_week.py for how the
 * WINNER is chosen (a Wilson-lower-bound confidence score, the same
 * technique aggregateKdByCountry uses in playerDuels.js, so a one-map hot
 * streak can't outrank a whole week of consistent play); the `rating`
 * shown here is still the player's real, unshrunk average either way.
 *
 * Renders nothing when player_week.json is absent (it's generated by
 * data_prep/build_player_week.py and may legitimately not exist yet).
 */
export default function PlayerOfWeekCard({ data, photosData, wide = false }) {
  const photoPath = data?.player ? photosData?.[data.player.toLowerCase()] : null
  const [photoLoadFailed, setPhotoLoadFailed] = useState(false)
  useEffect(() => {
    setPhotoLoadFailed(false)
  }, [data?.player])

  if (!data?.player) return null

  const hasPhoto = photoPath && !photoLoadFailed
  const photoSize = wide ? 'w-20 h-20' : 'w-16 h-16'

  const identity = (
    <div className={`flex items-center gap-3.5 ${wide ? 'sm:w-60' : ''} shrink-0`}>
      {/* Same photo-frame treatment as PlayerProfile's header: a blurred
          accent halo behind the EMPTY placeholder only (a real photo has
          its own colors/edges the halo just fights with). */}
      <div className={`relative ${photoSize} shrink-0`}>
        {!hasPhoto && (
          <div className="absolute inset-0 rounded-xl bg-accent/25 blur-2xl" aria-hidden="true" />
        )}
        <div className="relative w-full h-full rounded-xl bg-surface2 border border-hairline flex items-center justify-center overflow-hidden">
          {hasPhoto ? (
            <img
              src={`${import.meta.env.BASE_URL}${photoPath}`}
              alt={data.player}
              className="w-full h-full object-cover"
              onError={() => setPhotoLoadFailed(true)}
            />
          ) : (
            <svg viewBox="0 0 24 24" fill="none" className={wide ? 'w-10 h-10 text-muted/40' : 'w-8 h-8 text-muted/40'} aria-hidden="true">
              <circle cx="12" cy="8" r="4" stroke="currentColor" strokeWidth="1.5" />
              <path d="M4 20.5c0-4.42 3.58-7.5 8-7.5s8 3.08 8 7.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
            </svg>
          )}
        </div>
      </div>

      <div className="min-w-0 flex-1">
        <Link
          to={`/players/${encodeURIComponent(data.player)}`}
          className={`flex items-center gap-1.5 font-semibold text-ink transition-colors hover:text-accent-bright ${wide ? 'text-lg' : 'text-[15px]'}`}
        >
          {data.countryCode && (
            <Flag countryCode={data.countryCode} countryName={data.countryName} size={wide ? 14 : 12} />
          )}
          <span className="truncate">{data.player}</span>
        </Link>
        {data.team && (
          <Link
            to={`/teams/${encodeURIComponent(data.team)}`}
            className="mt-1 flex min-w-0 items-center text-[11px] text-muted transition-colors hover:text-ink"
          >
            <TeamLogo team={data.team} size={14} />
          </Link>
        )}
        <div className="mt-1.5 flex items-baseline gap-1">
          <span className={`font-display font-bold leading-none text-accent-bright ${wide ? 'text-2xl' : 'text-xl'}`}>
            {fmtRating(data.rating)}
          </span>
          <span className="text-[9px] uppercase tracking-wide text-muted/70">Rating</span>
        </div>
      </div>
    </div>
  )

  const stats = (
    <div className={`grid gap-1.5 ${wide ? 'grid-cols-3 sm:grid-cols-6 flex-1' : 'grid-cols-3'}`}>
      <Stat label="ACS" value={data.acs != null ? num(data.acs) : null} />
      <Stat label="K/D" value={data.kd != null ? data.kd.toFixed(2) : null} />
      <Stat label="ADR" value={data.adr != null ? num(data.adr) : null} />
      <Stat label="KAST" value={data.kast != null ? pct(data.kast, 0) : null} />
      <Stat label="HS%" value={data.hs != null ? pct(data.hs, 0) : null} />
      <Stat label="Maps" value={num(data.maps)} />
    </div>
  )

  const roundsCaption = (
    <p className={`text-[10px] text-muted/60 ${wide ? 'sm:text-right' : 'text-center'}`}>
      {num(data.rounds)} rounds this week
    </p>
  )

  return (
    <RailCard title={`Player of the week · ${dateRangeLabel(data.weekStart, data.weekEnd)}`}>
      {wide ? (
        <div className="p-4 flex flex-col sm:flex-row sm:items-center gap-5">
          {identity}
          <div className="hidden sm:block w-px self-stretch bg-hairline" aria-hidden="true" />
          <div className="flex-1 flex flex-col gap-1.5">
            {stats}
            {roundsCaption}
          </div>
        </div>
      ) : (
        <div className="p-4 flex flex-col gap-4">
          {identity}
          {stats}
          {roundsCaption}
        </div>
      )}
    </RailCard>
  )
}

function Stat({ label, value }) {
  return (
    <div className="rounded-lg bg-surface2/60 py-2 text-center">
      <div className="text-[13px] font-semibold tabular-nums text-ink">{value ?? '—'}</div>
      <div className="text-[9px] uppercase tracking-wide text-muted/70">{label}</div>
    </div>
  )
}
