import { Link } from 'react-router-dom'
import Flag from './Flag'
import TeamLogo from './TeamLogo'
import { RailCard } from './MatchRail'
import { rating as fmtRating, pct, num, dateRangeLabel } from '../lib/format'

/**
 * rft.gg's "PLAYER OF THE MONTH" panel, adapted to a rolling 7-day window
 * instead -- "Player of the Week", per direct request (a calendar month is
 * long relative to how often this should actually change against a season
 * with weekly brackets).
 *
 * Two deliberate departures from a literal copy:
 *  - rft.gg shows a player PHOTO. This site has none for anyone, so identity
 *    is carried by the flag + team logo it already uses everywhere else
 *    rather than adding a portrait pipeline for one card.
 *  - The sample size (maps/rounds) is stated outright. The week is often
 *    only partly played through, and a 1.45 rating off 4 maps means
 *    something different from a 1.45 off 30. Showing the denominator is the
 *    honest version -- there's no eligibility gate any more (removed by
 *    direct request; see build_player_week.py), so a thin sample CAN win,
 *    it just shrinks toward the week's own mean rather than being excluded.
 *
 * Renders nothing when player_week.json is absent (it's generated by
 * data_prep/build_player_week.py and may legitimately not exist yet).
 */
export default function PlayerOfWeekCard({ data }) {
  if (!data?.player) return null

  return (
    <RailCard title={`Player of the week · ${dateRangeLabel(data.weekStart, data.weekEnd)}`}>
      <div className="p-3">
        <div className="flex items-center gap-2.5">
          <div className="shrink-0 text-center">
            <div className="font-display text-2xl font-bold leading-none text-accent-bright">
              {fmtRating(data.rating)}
            </div>
            <div className="mt-0.5 text-[9px] uppercase tracking-wide text-muted/70">Rating</div>
          </div>
          <div className="min-w-0 flex-1">
            <Link
              to={`/players/${encodeURIComponent(data.player)}`}
              className="flex items-center gap-1.5 text-[13px] font-semibold text-ink transition-colors hover:text-accent-bright"
            >
              {data.countryCode && (
                <Flag countryCode={data.countryCode} countryName={data.countryName} size={11} />
              )}
              <span className="truncate">{data.player}</span>
            </Link>
            {data.team && (
              <Link
                to={`/teams/${encodeURIComponent(data.team)}`}
                className="mt-1 flex min-w-0 items-center text-[11px] text-muted transition-colors hover:text-ink"
              >
                <TeamLogo team={data.team} size={14} />
              </Link>
            )}
          </div>
        </div>

        <div className="mt-3 grid grid-cols-3 gap-1.5">
          <Stat label="ACS" value={data.acs != null ? num(data.acs) : null} />
          <Stat label="K/D" value={data.kd != null ? data.kd.toFixed(2) : null} />
          <Stat label="ADR" value={data.adr != null ? num(data.adr) : null} />
          <Stat label="KAST" value={data.kast != null ? pct(data.kast, 0) : null} />
          <Stat label="HS%" value={data.hs != null ? pct(data.hs, 0) : null} />
          <Stat label="Maps" value={num(data.maps)} />
        </div>

        <p className="mt-2 text-center text-[10px] text-muted/60">
          {num(data.rounds)} rounds this week
        </p>
      </div>
    </RailCard>
  )
}

function Stat({ label, value }) {
  return (
    <div className="rounded-lg bg-surface2/60 py-1.5 text-center">
      <div className="text-[12px] font-semibold tabular-nums text-ink">{value ?? '—'}</div>
      <div className="text-[9px] uppercase tracking-wide text-muted/70">{label}</div>
    </div>
  )
}
